language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "nobody@nobody.org"
branches:
  only:
  - master
env:
  global:
    secure: JENkehhUN7jGOB2WPqzskksoAkRSa6R1QttVsun47FAa8oedpAfRgk5R4OsEYHHt5TpA1KURmop9SRBw3y0J65+r+kFss4CaqLrTecRB6XCWZFyiIVpGu2hjv26ShIzthzf8jnShPlaOg7CT9YzzoEZ7J5ljmyk8Wq/UAdC+ytamE78dHJKK0zSggXKmjcZEvXEg7EbCis8dqpft5EyAR13IbdGxWisyMK0UIId9JKnQiArCdvAwU477I5mm0RSJJR3HE/BUFjKj2cHsK1iViI1PNwczDdhs+aTN4bUf8LEqusUFw2H4q9eCkMZF2SYh9+OxqE8+5W2WKkKJk/AEWZVJhebt5h0yK4i2YmPOl3vTRIWlU2HtjmkYVNVB5tlTsJ33BjZuR3MWdoUmXvEVZgooAfzDlqDdksIbjJ12AN3R/A5YeUlK/fBWB3RT2TybC8iFKwq2R36rnGTNUE/c2acXXf1iDAKvuiw4WOvv8du7ZYo9iNsfHK5lXiaDRWHkFApmBmAWWmtEVC/VYL4ElE7z1XdZuIQ5mnWsBkLaWw3bINDbQcK08OacNAkMJPvXdKewJqCSpCA+1FCG1G3WempLRg4KzXstoHfkmv8futU1JBmnyfs9O0vgxBqQPFy+xl1cGmoNKx/bFWKrX/p175DNuizGUTZEk9Z1/X9gyS0=
notifications:
  hipchat:
    rooms:
      secure: hI5E3zqdF1wklSpuY+s4hXEEfpWa1Pg2b+DTBsveUucks/i81JtfOtyYrIg0VXMPufSawDspV/kpskU+mItNdgKk63iCBAuTdBcNc5za3i6ohP4td1fIJlGVenksLVlTSwZKSe6K1K6QOHij/8K8yQfYjxhzsvfOvEGeqXVVubUgId9N3QJa7c321YB6RX/MGaZp/V8tnbbjWN5TF+ld67Zd7Yhz26OBjashyTUFeOHKv005WHV8Vq1sSdsRi9/wKgHfzKJKXgjrUUBlLG6lQmkOqDJmg7/mPSg0fNloBmfIzmK9vwxG6MCxOgIyxvem269QY9dnOWlKxv8vfHdynLW3DzDQ96uUhAlPDCOv+gunRbh9+CPZHFMgGckBXcquhx+w0kdlic73uWZHKPL1aG/4g+lbObr8v5Mtnuc5TBnBGtL0HqsTsmHtAH1s3V2LSKUdD+y/zTqyr4W0waO+ebtVmZTazrDGcY5o3Op11B/4KacXToO1ij4uC40Gp0TgPbPg0U9Ogo3E1Et4LYgMY0xnTyKVBMEbNOl8TTLxL4sCQ3EJU0Hso02quCRgxPFq5TapmJtvIZPhJcsHo2ENIx6iqRpAzJu3ec9BEVbduqh7+eKHtg6DgA6XwSmlxTFQN07apL7AyVZaFiyKX4W1mypX/PP6i+YleaBu1yNxYC8=
